package tk.mybatis.mapper.model;

import java.math.BigDecimal;
import java.util.Date;

public class HaClaimMedicalBillingDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.claim_policy_individual_id
     *
     * @mbggenerated
     */
    private Long claimPolicyIndividualId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.source_policy_id
     *
     * @mbggenerated
     */
    private Long sourcePolicyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.claim_application_id
     *
     * @mbggenerated
     */
    private Long claimApplicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.medical_billing_no
     *
     * @mbggenerated
     */
    private String medicalBillingNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.report_no
     *
     * @mbggenerated
     */
    private String reportNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.virtual_receipt_no
     *
     * @mbggenerated
     */
    private String virtualReceiptNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.tax_receipt_no
     *
     * @mbggenerated
     */
    private String taxReceiptNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.hospital_id
     *
     * @mbggenerated
     */
    private String hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.hospital_name
     *
     * @mbggenerated
     */
    private String hospitalName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.hospital_type
     *
     * @mbggenerated
     */
    private String hospitalType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.hospital_class
     *
     * @mbggenerated
     */
    private String hospitalClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.hospital_rank
     *
     * @mbggenerated
     */
    private String hospitalRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.hospital_property
     *
     * @mbggenerated
     */
    private String hospitalProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.hospital_department
     *
     * @mbggenerated
     */
    private String hospitalDepartment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.is_accepted_hosptial
     *
     * @mbggenerated
     */
    private String isAcceptedHosptial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.is_nssf_hosptial
     *
     * @mbggenerated
     */
    private String isNssfHosptial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.cure_type
     *
     * @mbggenerated
     */
    private String cureType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.medical_start_date
     *
     * @mbggenerated
     */
    private Date medicalStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.medical_end_date
     *
     * @mbggenerated
     */
    private Date medicalEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.medical_count
     *
     * @mbggenerated
     */
    private Integer medicalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.bill_type
     *
     * @mbggenerated
     */
    private String billType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.document_type
     *
     * @mbggenerated
     */
    private String documentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.document_code
     *
     * @mbggenerated
     */
    private String documentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.document_info
     *
     * @mbggenerated
     */
    private String documentInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.primary_disease_name
     *
     * @mbggenerated
     */
    private String primaryDiseaseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.primary_disease_code
     *
     * @mbggenerated
     */
    private String primaryDiseaseCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.fee_amount
     *
     * @mbggenerated
     */
    private BigDecimal feeAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.ownexpense_amount
     *
     * @mbggenerated
     */
    private BigDecimal ownexpenseAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.selfpay_amount
     *
     * @mbggenerated
     */
    private BigDecimal selfpayAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.nonresponsible_amount
     *
     * @mbggenerated
     */
    private BigDecimal nonresponsibleAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.medicare_amount
     *
     * @mbggenerated
     */
    private BigDecimal medicareAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.other_amount
     *
     * @mbggenerated
     */
    private BigDecimal otherAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.reasonable_amount
     *
     * @mbggenerated
     */
    private BigDecimal reasonableAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.is_settlement
     *
     * @mbggenerated
     */
    private String isSettlement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.gmt_created
     *
     * @mbggenerated
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.creator
     *
     * @mbggenerated
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.modifier
     *
     * @mbggenerated
     */
    private String modifier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.fee_memo
     *
     * @mbggenerated
     */
    private String feeMemo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.hospital_custom_name
     *
     * @mbggenerated
     */
    private String hospitalCustomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.original
     *
     * @mbggenerated
     */
    private String original;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.deduction_amount
     *
     * @mbggenerated
     */
    private BigDecimal deductionAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.hospital_city
     *
     * @mbggenerated
     */
    private String hospitalCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ha_claim_medical_billing.hospital_code
     *
     * @mbggenerated
     */
    private String hospitalCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.id
     *
     * @return the value of ha_claim_medical_billing.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.id
     *
     * @param id the value for ha_claim_medical_billing.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.claim_policy_individual_id
     *
     * @return the value of ha_claim_medical_billing.claim_policy_individual_id
     *
     * @mbggenerated
     */
    public Long getClaimPolicyIndividualId() {
        return claimPolicyIndividualId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.claim_policy_individual_id
     *
     * @param claimPolicyIndividualId the value for ha_claim_medical_billing.claim_policy_individual_id
     *
     * @mbggenerated
     */
    public void setClaimPolicyIndividualId(Long claimPolicyIndividualId) {
        this.claimPolicyIndividualId = claimPolicyIndividualId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.source_policy_id
     *
     * @return the value of ha_claim_medical_billing.source_policy_id
     *
     * @mbggenerated
     */
    public Long getSourcePolicyId() {
        return sourcePolicyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.source_policy_id
     *
     * @param sourcePolicyId the value for ha_claim_medical_billing.source_policy_id
     *
     * @mbggenerated
     */
    public void setSourcePolicyId(Long sourcePolicyId) {
        this.sourcePolicyId = sourcePolicyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.claim_application_id
     *
     * @return the value of ha_claim_medical_billing.claim_application_id
     *
     * @mbggenerated
     */
    public Long getClaimApplicationId() {
        return claimApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.claim_application_id
     *
     * @param claimApplicationId the value for ha_claim_medical_billing.claim_application_id
     *
     * @mbggenerated
     */
    public void setClaimApplicationId(Long claimApplicationId) {
        this.claimApplicationId = claimApplicationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.medical_billing_no
     *
     * @return the value of ha_claim_medical_billing.medical_billing_no
     *
     * @mbggenerated
     */
    public String getMedicalBillingNo() {
        return medicalBillingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.medical_billing_no
     *
     * @param medicalBillingNo the value for ha_claim_medical_billing.medical_billing_no
     *
     * @mbggenerated
     */
    public void setMedicalBillingNo(String medicalBillingNo) {
        this.medicalBillingNo = medicalBillingNo == null ? null : medicalBillingNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.report_no
     *
     * @return the value of ha_claim_medical_billing.report_no
     *
     * @mbggenerated
     */
    public String getReportNo() {
        return reportNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.report_no
     *
     * @param reportNo the value for ha_claim_medical_billing.report_no
     *
     * @mbggenerated
     */
    public void setReportNo(String reportNo) {
        this.reportNo = reportNo == null ? null : reportNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.virtual_receipt_no
     *
     * @return the value of ha_claim_medical_billing.virtual_receipt_no
     *
     * @mbggenerated
     */
    public String getVirtualReceiptNo() {
        return virtualReceiptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.virtual_receipt_no
     *
     * @param virtualReceiptNo the value for ha_claim_medical_billing.virtual_receipt_no
     *
     * @mbggenerated
     */
    public void setVirtualReceiptNo(String virtualReceiptNo) {
        this.virtualReceiptNo = virtualReceiptNo == null ? null : virtualReceiptNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.tax_receipt_no
     *
     * @return the value of ha_claim_medical_billing.tax_receipt_no
     *
     * @mbggenerated
     */
    public String getTaxReceiptNo() {
        return taxReceiptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.tax_receipt_no
     *
     * @param taxReceiptNo the value for ha_claim_medical_billing.tax_receipt_no
     *
     * @mbggenerated
     */
    public void setTaxReceiptNo(String taxReceiptNo) {
        this.taxReceiptNo = taxReceiptNo == null ? null : taxReceiptNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.hospital_id
     *
     * @return the value of ha_claim_medical_billing.hospital_id
     *
     * @mbggenerated
     */
    public String getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.hospital_id
     *
     * @param hospitalId the value for ha_claim_medical_billing.hospital_id
     *
     * @mbggenerated
     */
    public void setHospitalId(String hospitalId) {
        this.hospitalId = hospitalId == null ? null : hospitalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.hospital_name
     *
     * @return the value of ha_claim_medical_billing.hospital_name
     *
     * @mbggenerated
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.hospital_name
     *
     * @param hospitalName the value for ha_claim_medical_billing.hospital_name
     *
     * @mbggenerated
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName == null ? null : hospitalName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.hospital_type
     *
     * @return the value of ha_claim_medical_billing.hospital_type
     *
     * @mbggenerated
     */
    public String getHospitalType() {
        return hospitalType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.hospital_type
     *
     * @param hospitalType the value for ha_claim_medical_billing.hospital_type
     *
     * @mbggenerated
     */
    public void setHospitalType(String hospitalType) {
        this.hospitalType = hospitalType == null ? null : hospitalType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.hospital_class
     *
     * @return the value of ha_claim_medical_billing.hospital_class
     *
     * @mbggenerated
     */
    public String getHospitalClass() {
        return hospitalClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.hospital_class
     *
     * @param hospitalClass the value for ha_claim_medical_billing.hospital_class
     *
     * @mbggenerated
     */
    public void setHospitalClass(String hospitalClass) {
        this.hospitalClass = hospitalClass == null ? null : hospitalClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.hospital_rank
     *
     * @return the value of ha_claim_medical_billing.hospital_rank
     *
     * @mbggenerated
     */
    public String getHospitalRank() {
        return hospitalRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.hospital_rank
     *
     * @param hospitalRank the value for ha_claim_medical_billing.hospital_rank
     *
     * @mbggenerated
     */
    public void setHospitalRank(String hospitalRank) {
        this.hospitalRank = hospitalRank == null ? null : hospitalRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.hospital_property
     *
     * @return the value of ha_claim_medical_billing.hospital_property
     *
     * @mbggenerated
     */
    public String getHospitalProperty() {
        return hospitalProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.hospital_property
     *
     * @param hospitalProperty the value for ha_claim_medical_billing.hospital_property
     *
     * @mbggenerated
     */
    public void setHospitalProperty(String hospitalProperty) {
        this.hospitalProperty = hospitalProperty == null ? null : hospitalProperty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.hospital_department
     *
     * @return the value of ha_claim_medical_billing.hospital_department
     *
     * @mbggenerated
     */
    public String getHospitalDepartment() {
        return hospitalDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.hospital_department
     *
     * @param hospitalDepartment the value for ha_claim_medical_billing.hospital_department
     *
     * @mbggenerated
     */
    public void setHospitalDepartment(String hospitalDepartment) {
        this.hospitalDepartment = hospitalDepartment == null ? null : hospitalDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.is_accepted_hosptial
     *
     * @return the value of ha_claim_medical_billing.is_accepted_hosptial
     *
     * @mbggenerated
     */
    public String getIsAcceptedHosptial() {
        return isAcceptedHosptial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.is_accepted_hosptial
     *
     * @param isAcceptedHosptial the value for ha_claim_medical_billing.is_accepted_hosptial
     *
     * @mbggenerated
     */
    public void setIsAcceptedHosptial(String isAcceptedHosptial) {
        this.isAcceptedHosptial = isAcceptedHosptial == null ? null : isAcceptedHosptial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.is_nssf_hosptial
     *
     * @return the value of ha_claim_medical_billing.is_nssf_hosptial
     *
     * @mbggenerated
     */
    public String getIsNssfHosptial() {
        return isNssfHosptial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.is_nssf_hosptial
     *
     * @param isNssfHosptial the value for ha_claim_medical_billing.is_nssf_hosptial
     *
     * @mbggenerated
     */
    public void setIsNssfHosptial(String isNssfHosptial) {
        this.isNssfHosptial = isNssfHosptial == null ? null : isNssfHosptial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.cure_type
     *
     * @return the value of ha_claim_medical_billing.cure_type
     *
     * @mbggenerated
     */
    public String getCureType() {
        return cureType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.cure_type
     *
     * @param cureType the value for ha_claim_medical_billing.cure_type
     *
     * @mbggenerated
     */
    public void setCureType(String cureType) {
        this.cureType = cureType == null ? null : cureType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.medical_start_date
     *
     * @return the value of ha_claim_medical_billing.medical_start_date
     *
     * @mbggenerated
     */
    public Date getMedicalStartDate() {
        return medicalStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.medical_start_date
     *
     * @param medicalStartDate the value for ha_claim_medical_billing.medical_start_date
     *
     * @mbggenerated
     */
    public void setMedicalStartDate(Date medicalStartDate) {
        this.medicalStartDate = medicalStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.medical_end_date
     *
     * @return the value of ha_claim_medical_billing.medical_end_date
     *
     * @mbggenerated
     */
    public Date getMedicalEndDate() {
        return medicalEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.medical_end_date
     *
     * @param medicalEndDate the value for ha_claim_medical_billing.medical_end_date
     *
     * @mbggenerated
     */
    public void setMedicalEndDate(Date medicalEndDate) {
        this.medicalEndDate = medicalEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.medical_count
     *
     * @return the value of ha_claim_medical_billing.medical_count
     *
     * @mbggenerated
     */
    public Integer getMedicalCount() {
        return medicalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.medical_count
     *
     * @param medicalCount the value for ha_claim_medical_billing.medical_count
     *
     * @mbggenerated
     */
    public void setMedicalCount(Integer medicalCount) {
        this.medicalCount = medicalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.bill_type
     *
     * @return the value of ha_claim_medical_billing.bill_type
     *
     * @mbggenerated
     */
    public String getBillType() {
        return billType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.bill_type
     *
     * @param billType the value for ha_claim_medical_billing.bill_type
     *
     * @mbggenerated
     */
    public void setBillType(String billType) {
        this.billType = billType == null ? null : billType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.document_type
     *
     * @return the value of ha_claim_medical_billing.document_type
     *
     * @mbggenerated
     */
    public String getDocumentType() {
        return documentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.document_type
     *
     * @param documentType the value for ha_claim_medical_billing.document_type
     *
     * @mbggenerated
     */
    public void setDocumentType(String documentType) {
        this.documentType = documentType == null ? null : documentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.document_code
     *
     * @return the value of ha_claim_medical_billing.document_code
     *
     * @mbggenerated
     */
    public String getDocumentCode() {
        return documentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.document_code
     *
     * @param documentCode the value for ha_claim_medical_billing.document_code
     *
     * @mbggenerated
     */
    public void setDocumentCode(String documentCode) {
        this.documentCode = documentCode == null ? null : documentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.document_info
     *
     * @return the value of ha_claim_medical_billing.document_info
     *
     * @mbggenerated
     */
    public String getDocumentInfo() {
        return documentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.document_info
     *
     * @param documentInfo the value for ha_claim_medical_billing.document_info
     *
     * @mbggenerated
     */
    public void setDocumentInfo(String documentInfo) {
        this.documentInfo = documentInfo == null ? null : documentInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.remark
     *
     * @return the value of ha_claim_medical_billing.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.remark
     *
     * @param remark the value for ha_claim_medical_billing.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.primary_disease_name
     *
     * @return the value of ha_claim_medical_billing.primary_disease_name
     *
     * @mbggenerated
     */
    public String getPrimaryDiseaseName() {
        return primaryDiseaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.primary_disease_name
     *
     * @param primaryDiseaseName the value for ha_claim_medical_billing.primary_disease_name
     *
     * @mbggenerated
     */
    public void setPrimaryDiseaseName(String primaryDiseaseName) {
        this.primaryDiseaseName = primaryDiseaseName == null ? null : primaryDiseaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.primary_disease_code
     *
     * @return the value of ha_claim_medical_billing.primary_disease_code
     *
     * @mbggenerated
     */
    public String getPrimaryDiseaseCode() {
        return primaryDiseaseCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.primary_disease_code
     *
     * @param primaryDiseaseCode the value for ha_claim_medical_billing.primary_disease_code
     *
     * @mbggenerated
     */
    public void setPrimaryDiseaseCode(String primaryDiseaseCode) {
        this.primaryDiseaseCode = primaryDiseaseCode == null ? null : primaryDiseaseCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.fee_amount
     *
     * @return the value of ha_claim_medical_billing.fee_amount
     *
     * @mbggenerated
     */
    public BigDecimal getFeeAmount() {
        return feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.fee_amount
     *
     * @param feeAmount the value for ha_claim_medical_billing.fee_amount
     *
     * @mbggenerated
     */
    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.ownexpense_amount
     *
     * @return the value of ha_claim_medical_billing.ownexpense_amount
     *
     * @mbggenerated
     */
    public BigDecimal getOwnexpenseAmount() {
        return ownexpenseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.ownexpense_amount
     *
     * @param ownexpenseAmount the value for ha_claim_medical_billing.ownexpense_amount
     *
     * @mbggenerated
     */
    public void setOwnexpenseAmount(BigDecimal ownexpenseAmount) {
        this.ownexpenseAmount = ownexpenseAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.selfpay_amount
     *
     * @return the value of ha_claim_medical_billing.selfpay_amount
     *
     * @mbggenerated
     */
    public BigDecimal getSelfpayAmount() {
        return selfpayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.selfpay_amount
     *
     * @param selfpayAmount the value for ha_claim_medical_billing.selfpay_amount
     *
     * @mbggenerated
     */
    public void setSelfpayAmount(BigDecimal selfpayAmount) {
        this.selfpayAmount = selfpayAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.nonresponsible_amount
     *
     * @return the value of ha_claim_medical_billing.nonresponsible_amount
     *
     * @mbggenerated
     */
    public BigDecimal getNonresponsibleAmount() {
        return nonresponsibleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.nonresponsible_amount
     *
     * @param nonresponsibleAmount the value for ha_claim_medical_billing.nonresponsible_amount
     *
     * @mbggenerated
     */
    public void setNonresponsibleAmount(BigDecimal nonresponsibleAmount) {
        this.nonresponsibleAmount = nonresponsibleAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.medicare_amount
     *
     * @return the value of ha_claim_medical_billing.medicare_amount
     *
     * @mbggenerated
     */
    public BigDecimal getMedicareAmount() {
        return medicareAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.medicare_amount
     *
     * @param medicareAmount the value for ha_claim_medical_billing.medicare_amount
     *
     * @mbggenerated
     */
    public void setMedicareAmount(BigDecimal medicareAmount) {
        this.medicareAmount = medicareAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.other_amount
     *
     * @return the value of ha_claim_medical_billing.other_amount
     *
     * @mbggenerated
     */
    public BigDecimal getOtherAmount() {
        return otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.other_amount
     *
     * @param otherAmount the value for ha_claim_medical_billing.other_amount
     *
     * @mbggenerated
     */
    public void setOtherAmount(BigDecimal otherAmount) {
        this.otherAmount = otherAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.reasonable_amount
     *
     * @return the value of ha_claim_medical_billing.reasonable_amount
     *
     * @mbggenerated
     */
    public BigDecimal getReasonableAmount() {
        return reasonableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.reasonable_amount
     *
     * @param reasonableAmount the value for ha_claim_medical_billing.reasonable_amount
     *
     * @mbggenerated
     */
    public void setReasonableAmount(BigDecimal reasonableAmount) {
        this.reasonableAmount = reasonableAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.is_settlement
     *
     * @return the value of ha_claim_medical_billing.is_settlement
     *
     * @mbggenerated
     */
    public String getIsSettlement() {
        return isSettlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.is_settlement
     *
     * @param isSettlement the value for ha_claim_medical_billing.is_settlement
     *
     * @mbggenerated
     */
    public void setIsSettlement(String isSettlement) {
        this.isSettlement = isSettlement == null ? null : isSettlement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.is_deleted
     *
     * @return the value of ha_claim_medical_billing.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.is_deleted
     *
     * @param isDeleted the value for ha_claim_medical_billing.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.gmt_created
     *
     * @return the value of ha_claim_medical_billing.gmt_created
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.gmt_created
     *
     * @param gmtCreated the value for ha_claim_medical_billing.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.creator
     *
     * @return the value of ha_claim_medical_billing.creator
     *
     * @mbggenerated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.creator
     *
     * @param creator the value for ha_claim_medical_billing.creator
     *
     * @mbggenerated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.gmt_modified
     *
     * @return the value of ha_claim_medical_billing.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.gmt_modified
     *
     * @param gmtModified the value for ha_claim_medical_billing.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.modifier
     *
     * @return the value of ha_claim_medical_billing.modifier
     *
     * @mbggenerated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.modifier
     *
     * @param modifier the value for ha_claim_medical_billing.modifier
     *
     * @mbggenerated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier == null ? null : modifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.fee_memo
     *
     * @return the value of ha_claim_medical_billing.fee_memo
     *
     * @mbggenerated
     */
    public String getFeeMemo() {
        return feeMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.fee_memo
     *
     * @param feeMemo the value for ha_claim_medical_billing.fee_memo
     *
     * @mbggenerated
     */
    public void setFeeMemo(String feeMemo) {
        this.feeMemo = feeMemo == null ? null : feeMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.hospital_custom_name
     *
     * @return the value of ha_claim_medical_billing.hospital_custom_name
     *
     * @mbggenerated
     */
    public String getHospitalCustomName() {
        return hospitalCustomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.hospital_custom_name
     *
     * @param hospitalCustomName the value for ha_claim_medical_billing.hospital_custom_name
     *
     * @mbggenerated
     */
    public void setHospitalCustomName(String hospitalCustomName) {
        this.hospitalCustomName = hospitalCustomName == null ? null : hospitalCustomName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.original
     *
     * @return the value of ha_claim_medical_billing.original
     *
     * @mbggenerated
     */
    public String getOriginal() {
        return original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.original
     *
     * @param original the value for ha_claim_medical_billing.original
     *
     * @mbggenerated
     */
    public void setOriginal(String original) {
        this.original = original == null ? null : original.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.deduction_amount
     *
     * @return the value of ha_claim_medical_billing.deduction_amount
     *
     * @mbggenerated
     */
    public BigDecimal getDeductionAmount() {
        return deductionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.deduction_amount
     *
     * @param deductionAmount the value for ha_claim_medical_billing.deduction_amount
     *
     * @mbggenerated
     */
    public void setDeductionAmount(BigDecimal deductionAmount) {
        this.deductionAmount = deductionAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.hospital_city
     *
     * @return the value of ha_claim_medical_billing.hospital_city
     *
     * @mbggenerated
     */
    public String getHospitalCity() {
        return hospitalCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.hospital_city
     *
     * @param hospitalCity the value for ha_claim_medical_billing.hospital_city
     *
     * @mbggenerated
     */
    public void setHospitalCity(String hospitalCity) {
        this.hospitalCity = hospitalCity == null ? null : hospitalCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ha_claim_medical_billing.hospital_code
     *
     * @return the value of ha_claim_medical_billing.hospital_code
     *
     * @mbggenerated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ha_claim_medical_billing.hospital_code
     *
     * @param hospitalCode the value for ha_claim_medical_billing.hospital_code
     *
     * @mbggenerated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode == null ? null : hospitalCode.trim();
    }
}